export class BrandType {
    constructor() {}

    static FETCH_FROMBRAND_PENDING = 'FETCH_FROMBRAND_PENDING';
    static FETCH_FROMBRAND_SUCCESS = 'FETCH_FROMBRAND_SUCCESS';
    static FETCH_FROMBRAND_ERROR = 'FETCH_FROMBRAND_ERROR';

    static FETCH_BRAND_PENDING = 'FETCH_BRAND_PENDING';
    static FETCH_BRAND_SUCCESS = 'FETCH_BRAND_SUCCESS';
    static FETCH_BRAND_ERROR = 'FETCH_BRAND_ERROR';
}

export default BrandType;