export class CustomerType {
    constructor() {}

    static FETCH_LOGIN_PENDING = 'FETCH_LOGIN_PENDING';
    static FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
    static FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR';
    static CREATE_REGISTER_PENDING = 'CREATE_REGISTER_PENDING';
    static CREATE_REGISTER_SUCCESS = 'CREATE_REGISTER_SUCCESS';
    static CREATE_REGISTER_ERROR = 'CREATE_REGISTER_ERROR';
}

export default CustomerType