export class ProductType {
    constructor() {}

    static FETCH_PRODUCTFILTER_PENDING = 'FETCH_PRODUCTFILTER_PENDING';
    static FETCH_PRODUCTFILTER_SUCCESS = 'FETCH_PRODUCTFILTER_SUCCESS';
    static FETCH_PRODUCTFILTER_ERROR = 'FETCH_PRODUCTFILTER_ERROR';
    static GET_PRODUCT_PENDING = 'GET_PRODUCT_PENDING';
    static GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
    static GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';
    static FETCH_SIMILARPRODUCT_PENDING = 'FETCH_SIMILARPRODUCT_PENDING';
    static FETCH_SIMILARPRODUCT_SUCCESS = 'FETCH_SIMILARPRODUCT_SUCCESS';
    static FETCH_SIMILARPRODUCT_ERROR = 'FETCH_SIMILARPRODUCT_ERROR';
}

export default ProductType