export class ProductType {
    constructor() {}

    static FETCH_PRODUCTFILTER_PENDING = 'FETCH_PRODUCTFILTER_PENDING'
    static FETCH_PRODUCTFILTER_SUCCESS = 'FETCH_PRODUCTFILTER_SUCCESS'
    static FETCH_PRODUCTFILTER_ERROR = 'FETCH_PRODUCTFILTER_ERROR'
}

export default ProductType