export * from  './commentCustomer/commentCustomer'
export * from  './formComment/formComment'
export * from  './fromBrand/fromBrand'
export * from  './imageProduct/imageProduct'
export * from  './infoProduct/infoProduct'
export * from  './similarProduct/similarProduct'